#!/bin/bash
set -e

cd "$(dirname "$0")/.."
docker build -t entitlements-app -f spec/acceptance/Dockerfile.entitlements-app .
docker run -w "/data/entitlements-app/" entitlements-app \
  bash -c "script/bootstrap && bin/rubocop "$@" lib/ spec/"
