FROM ruby:2.7.5-buster
LABEL maintainer="GitHub Security Ops <opensource+entitlements-app@github.com>"
ENV HOME /root
ENV RELEASE=buster
ENV container docker
WORKDIR /data/entitlements-app

# Install dependency packages for bootstrapping and running...
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    cmake \
    ldap-utils

# Install bundler
RUN gem install bundler -v 2.4.22

# Bootstrap files and caching for speed
COPY "vendor/cache/" "/data/entitlements-app/vendor/cache/"
COPY "script/" "/data/entitlements-app/script/"
COPY [".rubocop.yml", ".ruby-version", "entitlements-app.gemspec", "Gemfile", "Gemfile.lock", "/data/entitlements-app/"]
COPY "lib/version.rb" "/data/entitlements/lib/version.rb"

# Source Files
COPY "bin/" "/data/entitlements-app/bin/"
COPY "lib/" "/data/entitlements-app/lib/"
COPY "spec/" "/data/entitlements-app/spec/"
