name: Combine PRs

on:
  schedule:
    - cron: "0 1 * * 3" # Wednesday at 01:00
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      # Using the GitHub App located here: https://github.com/organizations/github/settings/apps/combine-prs
      # Action docs can be found here: https://github.com/marketplace/actions/use-app-token
      # IMPORTANT: GitHub App settings can be found here: https://github.com/organizations/github/settings/installations/33545003
      - name: Use GitHub App Token
        uses: wow-actions/use-app-token@d7957e08172ca2e8e49b35b8d266ad585885edc7 # pin@v2.0.2
        id: generate_token
        with:
          app_id: ${{ secrets.COMBINE_PRS_APP_ID }}
          private_key: ${{ secrets.COMBINE_PRS_PRIVATE_KEY }}
          fallback: ${{ secrets.GITHUB_TOKEN }} # fall back to the default token if the app token is not available

      - name: combine-prs
        uses: github/combine-prs@95a545611cfb1b3c204fbe5637e77326fcfef11c # pin@v1.0.0
        with:
          github_token: ${{ steps.generate_token.outputs.BOT_TOKEN }} # A GitHub app token generated by the previous step
