name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  rubocop:
    name: runner / rspec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.1.2', '3.2.2', '3.3.0', '3.3.1' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@1198b074305f9356bd56dd4b311757cc0dab2f1c # pin@v1.175.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - run: script/test -d -k
